/* Configuration for ff3_ada generated by Alire */
#ifndef FF3_ADA_CONFIG_H
#define FF3_ADA_CONFIG_H

#define CRATE_VERSION "1.0.0"
#define CRATE_NAME "ff3_ada"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
