# Simple stack configuration for offline build
resolver: lts-20.26

packages:
- .

extra-deps:
- crypton-1.0.4@sha256:353391cc2cc583cf5e44c35c46b7a548a218037f2249c40a9712e00d7c46580c,14513

# Use system GHC if available
system-ghc: true

# Allow newer versions of dependencies
allow-newer: true
allow-newer-deps:
- crypton
- integer-gmp
- containers
- vector
- aeson
- text
- bytestring